[2016-10-18 19:12:21 +0000] [4654] [INFO] Starting gunicorn 19.4.5
[2016-10-18 19:12:21 +0000] [4654] [INFO] Listening at: http://127.0.0.1:8080 (4654)
[2016-10-18 19:12:21 +0000] [4654] [INFO] Using worker: sync
[2016-10-18 19:12:21 +0000] [4660] [INFO] Booting worker with pid: 4660
[2016-10-18 19:12:21 +0000] [4660] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
[2016-10-18 19:12:21 +0000] [4660] [INFO] Worker exiting (pid: 4660)
[2016-10-18 19:12:21 +0000] [4654] [INFO] Shutting down: Master
[2016-10-18 19:12:21 +0000] [4654] [INFO] Reason: Worker failed to boot.
[2016-10-18 19:14:37 +0000] [4698] [INFO] Starting gunicorn 19.4.5
[2016-10-18 19:14:37 +0000] [4698] [INFO] Listening at: http://127.0.0.1:8080 (4698)
[2016-10-18 19:14:37 +0000] [4698] [INFO] Using worker: sync
[2016-10-18 19:14:37 +0000] [4704] [INFO] Booting worker with pid: 4704
[2016-10-18 19:14:37 +0000] [4704] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
[2016-10-18 19:14:37 +0000] [4704] [INFO] Worker exiting (pid: 4704)
[2016-10-18 19:14:37 +0000] [4698] [INFO] Shutting down: Master
[2016-10-18 19:14:37 +0000] [4698] [INFO] Reason: Worker failed to boot.
[2016-10-18 19:19:38 +0000] [4799] [INFO] Starting gunicorn 19.4.5
[2016-10-18 19:19:38 +0000] [4799] [INFO] Listening at: http://127.0.0.1:8080 (4799)
[2016-10-18 19:19:38 +0000] [4799] [INFO] Using worker: sync
[2016-10-18 19:19:38 +0000] [4805] [INFO] Booting worker with pid: 4805
[2016-10-18 19:19:38 +0000] [4805] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
Traceback (most recent call last):
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/andy/projects/projectDZ2/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named application.wsgi
[2016-10-18 19:19:38 +0000] [4805] [INFO] Worker exiting (pid: 4805)
[2016-10-18 19:19:38 +0000] [4799] [INFO] Shutting down: Master
[2016-10-18 19:19:38 +0000] [4799] [INFO] Reason: Worker failed to boot.
